{
 "title": "Metrics dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "predict_response_duration_sum / predict_response_duration_count"
    }
   ]
  },
  {
   "title": "Predictions rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(num_pred[30s])" }
   ]
  },
  {
   "title": "Percentage of empty predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "percentage_empty" }
   ]
  },
  {
   "title": "User satisfaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "user_satisfaction" }
   ]
  },
  {
   "title": "User satisfaction VS percentage of empty predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "user_satisfaction" },
    { "expr": "percentage_empty" }
   ]
  },
  {
   "title": "User satisfaction VS prediction rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "user_satisfaction" },
    { "expr": "rate(num_pred[30s])" }
   ]
  }
 ]
}