additionalPrometheusRulesMap:
  custom-rules:
    groups:
    - name: UndesirableDeploymentAlerts
      rules:
      - alert: UsersUnsatisfied
        expr: num_pred > 2 and user_satisfaction < 0.5
        for: 1s
        labels:
          severity: critical
          rollback: "true"
        annotations:
          summary: Users indicate they are unsatisfied with the current prediction performance.
      - alert: TooManyEmpty
        expr: num_pred > 10 and percentage_empty >= 0.1
        for: 1s
        labels:
          severity: critical
          rollback: "true"
        annotations:
          summary: Returning too many undesirable empty responses
      - alert: ResponseTimeTooLarge
        expr: predict_response_duration_sum / predict_response_duration_count > 200
        for: 1s
        labels:
          severity: critical
          rollback: "true"
        annotations:
          summary: Users are waiting too long for a response from our machine learning endpoints.
