additionalPrometheusRulesMap:
  custom-rules:
    groups:
    - name: UndesirableDeploymentAlerts
      rules:
      - alert: UsersUnsatisfied
        expr: num_pred > 2 and user_satisfaction < 0.5
        for: 1s
        labels:
          severity: critical
          rollback: "true"
        annotations:
          summary: Users indicate they are unsatisfied with the current prediction performance.
