apiVersion: apps/v1
kind: Deployment
metadata:
  name: remla-deployment
  labels:
    app: remla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: remla-app
  template:
    metadata:
      labels:
        app: remla-app
    spec:
      containers:
      - name: remla-app
        image: crpaulsen/remla-app
        command: ["tail"]
        args: ["-f", "/dev/null"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: remla-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: my-service
      port:
        number: 80

