apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  selector:
    app: remla-app
    color: blue
  ports:
    - port: 1234
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-monitor
  labels:
    release: promstack
spec:
  selector:
    matchLabels:
      app: my-service
  endpoints:
  - targetPort: 8080
    path: "/metrics"
    interval: 1s

