name: ci

on: [push]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build docker image
      run: |
        docker build . -t app  
    
    - name: Run Pylint with Dslinter plugin
      run: |
        docker run app pylint \
          --load-plugins=dslinter \
          --reports=y \
          src

    - name: Run unit tests
      - run: python -m unittest test_build_features.TestBuildFeatures

    - name: Run ML pipeline with DVC
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DVC_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DVC_SECRET_ACCESS_KEY }}
      run: |
        docker run \
          -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          app bash -c "dvc pull && dvc repro" 

