name: Static analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pylint
        pip install dslinter
    - name: Run Pylint with Dslinter plugin
      run: |
        pylint \
          --load-plugins=dslinter \
          --reports=y \
          src
